<a href="https://colab.research.google.com/github/nthanhkhang/Natural-Language-Processing/blob/main/Sentiment_Vietnamese.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [32]:
import pandas as pd
import nltk 
import numpy as np

In [33]:
!wget https://raw.githubusercontent.com/nthanhkhang/Natural-Language-Processing/main/Lecture%204%20Text%20classification/data/data%20-%20data.csv

--2021-01-24 04:02:44--  https://raw.githubusercontent.com/nthanhkhang/Natural-Language-Processing/main/Lecture%204%20Text%20classification/data/data%20-%20data.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2106051 (2.0M) [text/plain]
Saving to: ‘data - data.csv.1’

data - data.csv.1   100%[===================>]   2.01M  --.-KB/s    in 0.07s   

2021-01-24 04:02:45 (28.1 MB/s) - ‘data - data.csv.1’ saved [2106051/2106051]



In [34]:
filename = 'data - data.csv'
df = pd.read_csv(filename)
print(df.head(5))
print(df.shape)

                       comment label  Unnamed: 2 Unnamed: 3
0               Áo bao đẹp ạ!!   POS         NaN        NaN
1                  Tuyệt vời !   POS         NaN        NaN
2   2day ao khong giong trong.   NEG         NaN        NaN
3  Mùi thơm,bôi lên da mềm da.   POS         NaN        NaN
4            Vải đẹp, dày dặn.   POS         NaN        NaN
(31460, 4)


In [35]:
data = df.values
print(data.shape)

(31460, 4)


In [36]:
print(data[:10])

[['Áo bao đẹp ạ!!' 'POS' nan nan]
 ['Tuyệt vời !' 'POS' nan nan]
 ['2day ao khong giong trong.' 'NEG' nan nan]
 ['Mùi thơm,bôi lên da mềm da.' 'POS' nan nan]
 ['Vải đẹp, dày dặn.' 'POS' nan nan]
 ['Hàng rất đẹp, rất chi là ưng ý.' 'POS' nan nan]
 ['Chất lượng sản phẩm tốt, date dài.' 'POS' nan nan]
 ['Ăn nói và thái độ phục vụ tốt.' 'POS' nan nan]
 ['Đóng gói sản phẩm chắc chắn.' 'POS' nan nan]
 ['tất sờn hết ca chưa dùng mà vay r.' 'NEG' nan nan]]


In [37]:
lines = data[:,0]
labels = data[:,1]
print(lines[:20])
print(labels[:20])

['Áo bao đẹp ạ!!' 'Tuyệt vời !' '2day ao khong giong trong.'
 'Mùi thơm,bôi lên da mềm da.' 'Vải đẹp, dày dặn.'
 'Hàng rất đẹp, rất chi là ưng ý.' 'Chất lượng sản phẩm tốt, date dài.'
 'Ăn nói và thái độ phục vụ tốt.' 'Đóng gói sản phẩm chắc chắn.'
 'tất sờn hết ca chưa dùng mà vay r.' 'Shop phục vụ rất tốt.'
 'Mặc thì cũng đc.' 'Chất vải khỏi chê.' 'Thời gian giao hàng rất nhanh.'
 'Chất lượng sản phẩm tuyệt vời.'
 'vải hơi thô cứng Thời gian giao hàng nhanh.'
 'Chất lượng sp chưa thật sự đẹp nhe shop!'
 'Rất đáng tiền Thời gian giao hàng rất nhanh.'
 'Quần rất đẹp mặc vừa vặn.' 'Cảm giác mua hàng bị hớ thật tệ!']
['POS' 'POS' 'NEG' 'POS' 'POS' 'POS' 'POS' 'POS' 'POS' 'NEG' 'POS' 'NEU'
 'POS' 'POS' 'POS' 'POS' 'POS' 'POS' 'POS' 'NEG']


In [38]:
nltk.download('stopwords')
nltk.download('punkt')
from nltk.corpus import stopwords
def remove_stop_words(words):
    result = [i for i in words if i not in stopwords.words('english')]
    return result

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [39]:
sentences = [nltk.word_tokenize(sent) for sent in lines]
print(sentences[0])
remove_stop_words(sentences)

['Áo', 'bao', 'đẹp', 'ạ', '!', '!']


[['Áo', 'bao', 'đẹp', 'ạ', '!', '!'],
 ['Tuyệt', 'vời', '!'],
 ['2day', 'ao', 'khong', 'giong', 'trong', '.'],
 ['Mùi', 'thơm', ',', 'bôi', 'lên', 'da', 'mềm', 'da', '.'],
 ['Vải', 'đẹp', ',', 'dày', 'dặn', '.'],
 ['Hàng', 'rất', 'đẹp', ',', 'rất', 'chi', 'là', 'ưng', 'ý', '.'],
 ['Chất', 'lượng', 'sản', 'phẩm', 'tốt', ',', 'date', 'dài', '.'],
 ['Ăn', 'nói', 'và', 'thái', 'độ', 'phục', 'vụ', 'tốt', '.'],
 ['Đóng', 'gói', 'sản', 'phẩm', 'chắc', 'chắn', '.'],
 ['tất', 'sờn', 'hết', 'ca', 'chưa', 'dùng', 'mà', 'vay', 'r', '.'],
 ['Shop', 'phục', 'vụ', 'rất', 'tốt', '.'],
 ['Mặc', 'thì', 'cũng', 'đc', '.'],
 ['Chất', 'vải', 'khỏi', 'chê', '.'],
 ['Thời', 'gian', 'giao', 'hàng', 'rất', 'nhanh', '.'],
 ['Chất', 'lượng', 'sản', 'phẩm', 'tuyệt', 'vời', '.'],
 ['vải', 'hơi', 'thô', 'cứng', 'Thời', 'gian', 'giao', 'hàng', 'nhanh', '.'],
 ['Chất', 'lượng', 'sp', 'chưa', 'thật', 'sự', 'đẹp', 'nhe', 'shop', '!'],
 ['Rất', 'đáng', 'tiền', 'Thời', 'gian', 'giao', 'hàng', 'rất', 'nhanh', '.'],
 ['Quầ

In [40]:
from keras.preprocessing.text import Tokenizer 
tokenizer = Tokenizer()
tokenizer.fit_on_texts(sentences)

In [41]:
X = tokenizer.texts_to_matrix(sentences,mode='binary')
print(X)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [0. 1. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]]


In [42]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, labels, test_size=0.2, random_state=0)

In [43]:
from sklearn.linear_model import LogisticRegression  
model_LR = LogisticRegression()
model_LR = model_LR.fit(X_train,y_train)
y_pred = model_LR.predict(X_test)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


In [44]:
from sklearn.metrics import classification_report

print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

         NEG       0.70      0.73      0.72      1290
         NEU       0.41      0.23      0.30       946
         POS       0.85      0.93      0.89      4056

    accuracy                           0.78      6292
   macro avg       0.66      0.63      0.63      6292
weighted avg       0.76      0.78      0.76      6292



In [45]:
from sklearn.naive_bayes import MultinomialNB   
model_NB = MultinomialNB()
model_NB = model_NB.fit(X_train,y_train)
y_pred = model_NB.predict(X_test)

print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

         NEG       0.60      0.69      0.64      1290
         NEU       0.34      0.27      0.30       946
         POS       0.86      0.86      0.86      4056

    accuracy                           0.74      6292
   macro avg       0.60      0.61      0.60      6292
weighted avg       0.73      0.74      0.73      6292



In [46]:
input_sent = 'tất sờn hết ca chưa dùng mà vay r' 
tokens = nltk.word_tokenize(input_sent)
print(tokens)
X_input = tokenizer.texts_to_matrix([tokens],mode='binary')
print(X_input)

['tất', 'sờn', 'hết', 'ca', 'chưa', 'dùng', 'mà', 'vay', 'r']
[[0. 0. 0. ... 0. 0. 0.]]


In [47]:
y_pred = model_NB.predict(X_input)
print(y_pred)

['NEG']
