In [92]:
import pandas as pd

In [93]:
import nltk 
import numpy as np

In [96]:
filename = 'spam.csv'
df = pd.read_csv(filename,encoding = 'latin-1')
#df = pd.read_csv(filename,encoding = 'utf-8')
print(df.shape)
print(df.columns)
print(df.head(2))

(5572, 5)
Index(['v1', 'v2', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'], dtype='object')
    v1                                                 v2 Unnamed: 2  \
0  ham  Go until jurong point, crazy.. Available only ...        NaN   
1  ham                      Ok lar... Joking wif u oni...        NaN   

  Unnamed: 3 Unnamed: 4  
0        NaN        NaN  
1        NaN        NaN  


In [97]:
data = df.values
print(data.shape)

(5572, 5)


In [98]:
print(data[:2])

[['ham'
  'Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...'
  nan nan nan]
 ['ham' 'Ok lar... Joking wif u oni...' nan nan nan]]


In [50]:
lines = data[:,1]
labels = data[:,0]
print(lines[:5])
print(labels[:20])

['Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...'
 'Ok lar... Joking wif u oni...'
 "Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's"
 'U dun say so early hor... U c already then say...'
 "Nah I don't think he goes to usf, he lives around here though"]
['ham' 'ham' 'spam' 'ham' 'ham' 'spam' 'ham' 'ham' 'spam' 'spam' 'ham'
 'spam' 'spam' 'ham' 'ham' 'spam' 'ham' 'ham' 'ham' 'spam']


In [99]:
# tách từ trong từng câu 
sentences = [nltk.word_tokenize(sent) for sent in lines]
print(sentences[0])
# thêm 2 gram 


['Go', 'until', 'jurong', 'point', ',', 'crazy..', 'Available', 'only', 'in', 'bugis', 'n', 'great', 'world', 'la', 'e', 'buffet', '...', 'Cine', 'there', 'got', 'amore', 'wat', '...']


In [100]:
from keras.preprocessing.text import Tokenizer 
tokenizer = Tokenizer()
tokenizer.fit_on_texts(sentences)
# kiểm tra từ điểm tạo trong tokenizer
#print(tokenizer.word_index)

In [101]:
#texts_to_matrix(tokenizer, texts, mode = c("binary", "count", "tfidf", "freq"))
X = tokenizer.texts_to_matrix(sentences,mode='binary')
print(X)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 1. 1. 0.]
 [0. 0. 1. ... 0. 0. 1.]]


In [102]:
# chia tập train và tập test 
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, labels, test_size=0.2, random_state=0)

In [103]:
from sklearn.linear_model import LogisticRegression  
model_LR = LogisticRegression()
model_LR = model_LR.fit(X_train,y_train)
y_pred = model_LR.predict(X_test)

In [104]:
from sklearn.metrics import classification_report

print(classification_report(y_test,y_pred))


              precision    recall  f1-score   support

         ham       0.93      0.99      0.96        85
        spam       0.90      0.60      0.72        15

    accuracy                           0.93       100
   macro avg       0.92      0.79      0.84       100
weighted avg       0.93      0.93      0.92       100



In [71]:
from sklearn.naive_bayes import MultinomialNB   
model_NB = MultinomialNB()
model_NB = model_NB.fit(X_train,y_train)
y_pred = model_NB.predict(X_test)

print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

         ham       1.00      0.96      0.98        85
        spam       0.83      1.00      0.91        15

    accuracy                           0.97       100
   macro avg       0.92      0.98      0.95       100
weighted avg       0.97      0.97      0.97       100

